### ISSUE TITLE
Action failed: c:quickActionField$controller$doIni…nnot read property 'hasOwnProperty' of undefined]

### ISSUE THREAD

**Issue by mhofmann06** [jmdohn/Quick-Actions-Everywhere#11]
I'm trying to implement the Related List Button Example in the documentation. 

/apex/quickActionsEverywhere?action=LogACall&relatedId={!Account.Id}&relatedField=WhatId&title=Log A Call

When I click on the button I get the following error:
<img width="847" alt="Screen Shot 2019-11-22 at 11 09 58 AM" src="https://user-images.githubusercontent.com/58082953/69441394-a6616b80-0d18-11ea-9e4c-d0fd87f452bb.png">

I opened the Chrome Developer Tools Console and see its failing in the setIcons method of the quickActionFieldHelper.js Aura code. Specifically, trying access the icons variable. I added some console.log statements and see the icons variable is undefined and window.DataCache is an empty object. When it gets to line 94 "if(icons.hasOwnProperty(key)){" it fails because icons is undefined.

The only setup hiccup I had was the Named Credential wasn't deployed to my sandbox when I used the Github Deploy to Salesforce functionality. I manually created the Named Credential according to the documentation.

**Comment by jmdohn** [comment]
This was fixed with the below commit.  If you reinstall, you should not find the issue any longer.  It was a result of Salesforce not providing icons for all objects returned in the describe.
https://github.com/jmdohn/Quick-Actions-Everywhere/commit/54de3594f8f632c2bba8858d8d25c7f3efa16d29

**Comment by Teamlt99** [comment]
I just used the "Deploy to Salesforce" button and I'm still receiving the error as described in the original comment above. Am I getting the fix you described above when I click the "Deploy to Salesforce" button?
